export const surpriseMePrompts = [
  "Dracula walking down the street of New York City in the 1920s, black and white photography",
  "Synthwave aeroplane",
  "A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm",
  "A Space Shuttle flying above Cape Town, digital art",
  "a 3D render of a dragon made of crystals flying over a cityscape",
  "a painting of a tiger wearing a top hat and monocle",
  "a surrealist photograph of a giraffe playing the piano",
  "a digital illustration of a koala DJing a party",
  "a macro photograph of a bee wearing a tiny hat",
  "a 3D render of a robot cooking pancakes in a futuristic kitchen",
  "a cartoon of a penguin surfing on a giant wave",
  "a landscape oil painting of a forest filled with unicorns",
  "a digital illustration of a space shuttle flying through a rainbow",
  "a photograph of a dog dressed up as a superhero",
  "a pencil sketch of a robot garden filled with flowers",
  "a painting of a mermaid playing the guitar",
  "a surrealist portrait of a cat sitting on a floating cloud",
  "a digital illustration of a dinosaur riding a bicycle",
  "a macro photograph of a snail wearing a tiny backpack",
  "a 3D render of a futuristic city made entirely of candy",
  "a pencil sketch of a penguin reading a book in a tree",
  "a painting of a kangaroo playing the drums",
  "a surrealist landscape of a desert filled with giant cacti shaped like animals",
  "a digital illustration of a spacewalk on Jupiter",
  "a photograph of a bulldog wearing a tutu",
  "a pencil sketch of a robot having a picnic in a park",
  "a painting of a moose playing the cello",
  "a surrealist portrait of a cat riding a flying saucer",
  "a digital illustration of a dragon flying over a medieval castle",
  "a macro photograph of a caterpillar wearing a tiny hat",
  "a 3D render of a city floating in the clouds",
  "a pencil sketch of a penguin flying a kite",
  "a painting of a bear playing the saxophone",
  "a surrealist landscape of a forest filled with giant mushrooms",
  "a digital illustration of a spacewalk on Saturn",
  "a photograph of a poodle wearing a hat",
  "a pencil sketch of a robot playing soccer",
  "a painting of a lion playing the flute",
  "a surrealist portrait of a cat riding a flying broomstick",
  "a digital illustration of a dragon flying over a cityscape",
  "a macro photograph of a ladybug wearing a tiny hat",
  "a 3D render of a city built on a giant tree",
  "a pencil sketch of a penguin playing the guitar",
  "a painting of a raccoon playing the trumpet",
  "a surrealist landscape of a beach filled with giant shells",
  "a digital illustration of a spacewalk on Uranus",
  "a photograph of a dachshund wearing a bow tie",
  "a pencil sketch of a robot playing the piano",
  "a painting of a zebra playing the violin",
  "a surrealist portrait of a cat sitting on a floating moon",
  "a digital illustration of a dragon flying over a mountain range",
  "a macro photograph of a snail wearing a tiny hat",
  "a 3D render of a city built on a giant boat",
  "an armchair in the shape of an avocado",
  "a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers",
  "teddy bears shopping for groceries in Japan, ukiyo-e",
  "an oil painting by Matisse of a humanoid robot playing chess",
  "panda mad scientist mixing sparkling chemicals, digital art",
  "teddy bears shopping for groceries in Japan, ukiyo-e",
  "an oil painting by Matisse of a humanoid robot playing chess",
  "panda mad scientist mixing sparkling chemicals, digital art",
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  "3D render of a cute tropical fish in an aquarium on a dark blue background, digital art",
  "an astronaut lounging in a tropical resort in space, vaporwave",
  "an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background",
  "a stained glass window depicting a hamburger and french fries",
  "A synthwave style sunset above the reflecting water of the sea, digital art",
  "Two futuristic towers with a skybridge covered in lush foliage, digital art",
  "A 3D render of a rainbow colored hot air balloon flying above a reflective lake",
  "A comic book cover of a superhero wearing headphones",
  "A centered explosion of colorful powder on a black background",
  "A photo of a Samoyed dog with its tongue out hugging a white Siamese cat",
  "A photo of a white fur monster standing in a purple room",
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  "A Samurai riding a Horse on Mars, lomography.",
  "A realistic photograph of a young woman with blue eyes and blonde hair",
  "A man standing in front of a stargate to another dimension",
  "Spongebob Squarepants in the Blair Witch Project",
  "A velociraptor working at a hotdog stand, lomography",
  "A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens",
  "A BBQ that is alive, in the style of a Pixar animated movie",
  "A futuristic cyborg dance club, neon lights",
  "The long-lost Star Wars 1990 Japanese Anime",
  "A hamburger in the shape of a Rubik’s cube, professional food photography",
  "A Synthwave Hedgehog, Blade Runner Cyberpunk",
];
